[tool.poetry]
name = "notus"
version = "0.1.0"
description = ""
authors = ["Qwest1204 <workemailfordaniil@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
torch = "^2.7.0"
matplotlib = "^3.10.3"
polars = "^1.29.0"
notebook = "^7.4.2"
pandas = "^2.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
