encoder:
  vocab_size: 258
  embedding_dim: 256
  num_heads: 2
  num_layers: 1
  hash_len: 64
  d_ff: 100
  dropout: 0.1
  file_type_vocab: 213
  device: "cpu"
decoder:
  vocab_size: 258
  embedding_dim: 256
  num_heads: 16
  num_layers: 8
  d_ff: 200
  dropout: 0.05
  chunk_size: 2048
  device: "cpu"
dataset:
  vocab_size: 258
  seq_len: 2048
  path: "/Users/daniilogorodnikov/dataset/test"
train:
  num_epoch: 50
  lr: 0.01
  device: "cpu"
  precision: 32
  batch_size: 2
  num_workers: 0
  temproary_save: True

