encoder:
  vocab_size: 258
  embedding_dim: 2048
  num_heads: 8
  num_layers: 8
  hash_len: 64
  d_ff: 2048
  dropout: 0.1
  file_type_vocab: 213
  device: "cpu"
decoder:
  vocab_size: 258
  embedding_dim: 2048
  num_heads: 16
  num_layers: 16
  d_ff: 2048
  dropout: 0.1
  chunk_size: 3072
  device: "cpu"
dataset:
  vocab_size: 258
  seq_len: 3072
  path: "/Users/daniilogorodnikov/dataset/test"
train:
  num_epoch: 50
  interval4save: 500
  lr: 0.01
  device: "cpu"
  precision: 32
  batch_size: 2
  num_workers: 0

