encoder:
  vocab_size: 764
  embedding_dim: 256
  num_heads: 8
  num_layers: 16
  d_ff: 512
  dropout: 0.1
  hash_len: 512
  file_type_vocab: 213
  device: "cpu"
  attention_type: "MultiQueryAttention"
decoder:
