decoder:
   vocab_size: 258
   embedding_dim: 256
   latent_dim: 128
   num_heads: 4
   num_layers: 3
   d_ff: 512
   dropout: 0.1
   activation_type: 'gelu'

dataset:
  file_path: '/home/nv/dataset/enwik8'
  seq_len: 4096
  overlap: 256
  cache_dir: 'cache'
  force_rebuild: False

train:
  num_epoch: 50
  model_name_prefix: 'decoder_1.7M_latent_h4l3'
  accumulation_steps: 32
  lr: 0.001
  shuffle: True
  precision: 32
  batch_size: 4
  num_workers: 0
  pin_memory: True
  savedir: 'fileformer/transformer_model/weights/'

