name: test building model

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install Dependencies
        run:
          pip install -r requirements.txt

      - name: test_script
        run: python -m pytest --import-mode=append .

  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lowercase repository path
        id: repo
        run: |
          LOWERCASE_REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "LOWERCASE_REPO=$LOWERCASE_REPO" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.repo.outputs.LOWERCASE_REPO }}/notus-ray:${{ github.sha }}